# -*- coding: utf-8 -*-
"""
Django settings for Competition project.

Generated by 'django-admin startproject' using Django 3.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os
import environ
from pathlib import Path
import pymysql

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'l-_e!(dn76f$16i_&(*(j6#dl7e6)fmyt+^(p(jv233mzh3%ar'

RUN_ENV = os.getenv('RUN_ENV', default='development')
# SECURITY WARNING: don't run with debug turned on in production!
env = environ.Env(
    DEBUG=(bool, True),
    DEFAULT_NAME=(str, 'competition'),
    DEFAULT_USER=(str, 'root'),
    DEFAULT_PASSWORD=(str, '123456'),
    DEFAULT_HOST=(str, '127.0.0.1'),
    SLAVE_NAME=(str, 'ms_micro'),
    SLAVE_USER=(str, 'root'),
    SLAVE_PASSWORD=(str, '123456'),
    SLAVE_HOST=(str, '127.0.0.1'),
    DOMAIN_URL=(str, 'http://127.0.0.1:8000'),
    STATIC_ROOT=(str, os.path.join(BASE_DIR, 'static/classic/')),
    MEDIA_ROOT=(str, os.path.join(BASE_DIR, 'static/upload/')),
    STATIC_URL=(str, '/static/'),
    MEDIA_URL=(str, '/')
)
environ.Env.read_env()

DEBUG = env('DEBUG')

ALLOWED_HOSTS = ['*', ]

pymysql.version_info = (1, 4, 6, 'final', 0,)
pymysql.install_as_MySQLdb()

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

AUTH_USER_MODEL = 'user.User'
PASSWORD_HASHERS = (
    'django.contrib.auth.hashers.UnsaltedMD5PasswordHasher',
)

APP_LABELS = ['member', 'sku', 'cinema', ]

# 不让simpleui收集相关信息
SIMPLEUI_ANALYSIS = False
# js采用离线
SIMPLEUI_STATIC_OFFLINE = True

# DEFAULT_FILE_STORAGE = 'aliyun_oss2_storage.backends.AliyunMediaStorage'

# ACCESS_KEY_ID = "LTAI4GJDhgcvBXS4BT91CJbr"
# ACCESS_KEY_SECRET = "TjdDosFCiGTgvhWAVYSKVnav2Xynsi"
# END_POINT = "oss-cn-hangzhou.aliyuncs.com"
# BUCKET_NAME = "pupilary"
# ALIYUN_OSS_CNAME = ""  # 自定义域名，如果不需要可以不填写
# BUCKET_ACL_TYPE = "public-read"  # private, public-read, public-read-write

# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ckeditor',
    'ckeditor_uploader',
    'common',
    'filter',
    'apps.user',
    'apps.sku',
    'apps.member',
    'apps.cinema',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'), ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'common.context_processors.setting',
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.debug',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'django.template.context_processors.tz',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request',
            ],
            'debug': 'DEBUG',
        },
    },
]

WSGI_APPLICATION = 'wsgi.application'

DEFAULT_NAME = env('DEFAULT_NAME')
DEFAULT_USER = env('DEFAULT_USER')

DEFAULT_PASSWORD = env('DEFAULT_PASSWORD')
DEFAULT_HOST = env('DEFAULT_HOST')
SLAVE_NAME = env('SLAVE_NAME')
SLAVE_USER = env('SLAVE_USER')
SLAVE_PASSWORD = env('SLAVE_PASSWORD')
SLAVE_HOST = env('SLAVE_HOST')

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': DEFAULT_NAME,
        'USER': DEFAULT_USER,
        'PASSWORD': DEFAULT_PASSWORD,
        'HOST': DEFAULT_HOST,
        'PORT': '3306',
    },
    'slave': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': SLAVE_NAME,
        'USER': SLAVE_USER,
        'PASSWORD': SLAVE_PASSWORD,
        'HOST': SLAVE_HOST,
        'PORT': '3306',
    }
}

DATABASE_ROUTERS = ['common.app_db_router.SlaveDbRouter', ]

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline', 'Strikethrough', 'Subscript', 'Superscript', '-'],
            ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-'],
            ['Undo', 'Redo', 'NumberedList', 'BulletedList', '-'],
            ['JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', 'Link', 'Unlink', '-'],
            ['Templates', '-'],
            ['Image', 'Flash', 'Table', '-', ],
            ['Styles', 'Format', 'Font', 'Size', '-', ],
            ['Text Color', '-'],
            ['Maximize']
        ],
        'height': 391,
        'width': '100%',
        'language': 'zh-cn',
        'tabSpaces': 4,
    },
}

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/
# DOMAIN_URL = 'http://127.0.0.1:8000'
# STATIC_ROOT = os.path.join(BASE_DIR, 'static/classic/')
# MEDIA_ROOT = os.path.join(BASE_DIR, 'static/upload/')
# STATIC_URL = '/static/'
# MEDIA_URL = '/upload/'
# CKEDITOR_UPLOAD_PATH = 'upload/'
# CKEDITOR_IMAGE_BACKEND = 'pillow'

DOMAIN_URL = env('DOMAIN_URL')
STATIC_ROOT = env('STATIC_ROOT')
MEDIA_ROOT = env('MEDIA_ROOT')
STATIC_URL = env('STATIC_URL')
MEDIA_URL = env('MEDIA_URL')
CKEDITOR_UPLOAD_PATH = 'ckeditor/'
CKEDITOR_IMAGE_BACKEND = 'pillow'
